server:
  origin: http://nestjs-feeling-diary-frontend.s3-website-us-west-1.amazonaws.com

db:
  host: 'localhost'
  username: 'webprojUser'
  password: 'webprojUser'
  synchronize: false

jwt:
  secret: 'secretKey'